theme = "skgadi-w3"
languageCode = "en-us"
title = "Suresh Kumar Gadi"

baseurl = "https://skgadi.com/"
[params]
	CommonTitle = "Suresh Kumar Gadi"
	SubTitle = "Professor, FIME, UAdeC"
#	Copyright = "2017 Suresh Kumar Gadi"
#	email = "gadisureshkumar-at-gmail-dot-com"
	ORCID = "0000-0001-7974-7825"
	Scopus = "55608566000"
	GScholar = "efqOY90AAAAJ"
	GPlus = "+SureshKumarGadi"
	LinkedIn = "skgadi"
	Twitter = "SureshKumarGadi"
	Maps = "https://goo.gl/maps/8NrtjMajSUz"
	PayPal = "https://paypal.me/skgadi"
#	Phone = "+52 (1) 449 182 0153"
	Fax = "(+52 1) 871 757 0153"
	Address = "Carretera Torreón - Matamoros Km. 7.5, Ciudad Universitaria, Torreón, Coahuila, México, C.P. 27276"
	GoogleAnalyticsID = "UA-89998286-1"
	Author = "Suresh Kumar Gadi"
	SharingIcona = "true" #Type "true" show the sharing icons.
	SiteImageURL = "https://images.cooltext.com/4913938.png"
	SiteNameInText = "SKGadi.com"
	DefaultIconForMiniWindows = "fa-hand-o-right"
	
[params.meta.Keywords]
	name = ["skgadi", "suresh kumar gadi", "control digital"]
[params.meta.Description]
	name = "Dr. Suresh Kumar Gadi is currently working at Facultad de Ingenieria Mecanica y Eléctrica of Universidad Autónoma de Coahuila, Torreón campus as Professor since September 2015. Have three years of teaching cum research experience and six years of industrial experience."

[taxonomies]
	tag = "tags"
	category = "categories"

[[params.thanks]]
	identifier = "github"
	name = "GitHub"
	url = "https://github.com/"
	reason = "providing cloud based version control repository"
	weight = 0
[[params.thanks]]
	identifier = "netlify"
	name = "netlify"
	url = "https://www.netlify.com/"
	reason = "providing hosting"
	weight = 1
[[params.thanks]]
	identifier = "w3css"
	name = "W3.CSS"
	url = "https://www.w3schools.com/w3css/default.asp"
	reason = "providing CSS"
	weight = 2

	
	

[[menu.main]]
    identifier = "Research"
    name = "Research"
    url = "/research/"
	pre = "fa-flask"
	weight = 1


[[menu.main]]
    identifier = "Courses"
    name = "Courses"
    url = "/courses/"
	pre = "fa-book"
	weight = 3

[[menu.main]]
    identifier = "Tools"
    name = "Tools"
    url = "/tools/"
	pre = "fa-wrench"
	weight = 4

[[menu.main]]
    identifier = "Contact"
    name = "Contact"
    url = "/contact/"
	pre = "fa-vcard-o"
	weight = 10

[[menu.main]]
    identifier = "Resume"
    name = "Resume"
    url = "/resume/"
	pre = "fa-list-alt"
	weight = 11

[[menu.small]]
    identifier = "Education"
    name = "Education"
    url = "/education/"
	pre = "fa-university"
	weight = 1

[[menu.small]]
    identifier = "WorkExperience"
    name = "Work experience"
    url = "/work-experience/"
	pre = "fa-building-o"
	weight = 2

[[menu.small]]
    identifier = "Projects"
    name = "Projects"
    url = "/projects/"
	pre = "fa-cogs"
	weight = 3

[[menu.small]]
    identifier = "Posts"
    name = "Posts"
    url = "/posts/"
	pre = "fa-files-o"
	weight = 4

[[menu.small]]
    identifier = "Achievements"
    name = "achievements"
    url = "/achievements/"
	pre = "fa-trophy"
	weight = 5

[[menu.small]]
    identifier = "Tags"
    name = "Tags"
    url = "/tags/"
	pre = "fa-tags"
	weight = 6

[[menu.small]]
    identifier = "Categories"
    name = "Categories"
    url = "/categories/"
	pre = "fa-cubes"
	weight = 7

