theme = "skgadi-w3"
languageCode = "en-us"
title = "Suresh Kumar Gadi"

baseurl = "https://skgadi.com/"
[params]
	CommonTitle = "Suresh Kumar Gadi"
	SubTitle = "Research professor, FIME, UAdeC"
#	Copyright = "2017 Suresh Kumar Gadi"
#	email = "gadisureshkumar-at-gmail-dot-com"
	ORCID = "0000-0001-7974-7825"
	Scopus = "55608566000"
	GScholar = "efqOY90AAAAJ"
	GPlus = "+SureshKumarGadi"
	LinkedIn = "skgadi"
	Twitter = "SureshKumarGadi"
	Maps = "https://goo.gl/maps/8NrtjMajSUz"
#	Phone = "+52 (1) 449 182 0153"
	Fax = "+52 (1) 871 757 0153"
	Address = "Carretera Torreón - Matamoros Km. 7.5, Ciudad Universitaria, Torreón, Coahuila, México, C.P. 27276"
	GoogleAnalyticsID = "UA-89998286-1"
	Author = "Suresh Kumar Gadi"
	SharingIcona = "true" #Type "true" show the sharing icons.
	SiteImageURL = "https://images.cooltext.com/4913938.png"
	
[params.meta.Keywords]
	name = ["skgadi", "suresh kumar gadi", "control digital"]
[params.meta.Description]
	name = "Dr. Suresh Kumar Gadi is a research professor at the Universidad Autónoma de Coahuila, Torreón"

[taxonomies]
	tag = "tags"
	category = "categories"

[[params.thanks]]
	identifier = "github"
	name = "GitHub"
	url = "https://github.com/"
	reason = "providing cloud based version control repository"
	weight = 0
[[params.thanks]]
	identifier = "netlify"
	name = "netlify"
	url = "https://www.netlify.com/"
	reason = "providing hosting"
	weight = 1
[[params.thanks]]
	identifier = "w3css"
	name = "W3.CSS"
	url = "https://www.w3schools.com/w3css/default.asp"
	reason = "providing CSS"
	weight = 2

#[[menu.main]]
#    identifier = "Home"
#    name = "Home"
#    url = "/"
#	weight = 0

[[menu.main]]
    identifier = "Research"
    name = "Research"
    url = "/research/"
	pre = "<i class='fa fa-flask' aria-hidden='true'></i>"
	weight = 1

[[menu.main]]
    identifier = "Projects"
    name = "Projects"
    url = "/projects/"
	pre = "<i class='fa fa-cogs' aria-hidden='true'></i>"
	weight = 2

[[menu.main]]
    identifier = "Courses"
    name = "Courses"
    url = "/courses/"
	pre = "<i class='fa fa-book' aria-hidden='true'></i>"
	weight = 3

[[menu.main]]
    identifier = "Tools"
    name = "Tools"
    url = "/tools/"
	pre = "<i class='fa fa-wrench' aria-hidden='true'></i>"
	weight = 4

[[menu.main]]
    identifier = "Posts"
    name = "Posts"
    url = "/posts/"
	pre = "<i class='fa fa-files-o' aria-hidden='true'></i>"
	weight = 5

[[menu.main]]
    identifier = "Tags"
    name = "Tags"
    url = "/tags/"
	pre = "<i class='fa fa-tags' aria-hidden='true'></i>"
	weight = 6

[[menu.main]]
    identifier = "Categories"
    name = "Categories"
    url = "/categories/"
	pre = "<i class='fa fa-cubes' aria-hidden='true'></i>"
	weight = 7

[[menu.main]]
    identifier = "Education"
    name = "Education"
    url = "/education/"
	pre = "<i class='fa fa-university' aria-hidden='true'></i>"
	weight = 8

[[menu.main]]
    identifier = "WorkExperience"
    name = "Work experience"
    url = "/work-experience/"
	pre = "<i class='fa fa-building-o' aria-hidden='true'></i>"
	weight = 9

[[menu.main]]
    identifier = "Contact"
    name = "Contact"
    url = "/contact/"
	pre = "<i class='fa fa-vcard-o' aria-hidden='true'></i>"
	weight = 10
